# Generated by Django 4.2.18 on 2025-02-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="how_to_buy",
            field=models.TextField(blank=True, null=True, verbose_name="راهنمای خرید"),
        ),
    ]
