# Generated by Django 4.2.18 on 2025-02-08 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="عنوان"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="عنوان url"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("option", "Option"),
                            ("multi_option", "Multi Option"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Option",
            },
        ),
        migrations.CreateModel(
            name="OptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name": "Option Group",
                "verbose_name_plural": "Option Groups",
            },
        ),
        migrations.CreateModel(
            name="OptionGroupValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shop.optiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Group Value",
                "verbose_name_plural": "Option Group Values",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_variant", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=128, verbose_name="عنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="عنوان انگلیسی",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        unique=True,
                        verbose_name="عنوان url",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="کد کالا"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="موجودی"),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="قیمت")),
                ("is_special", models.BooleanField(default=False, verbose_name="ویژه")),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="درصد تخفیف"
                    ),
                ),
                (
                    "discounted_price",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="قیمت با تخفیف"
                    ),
                ),
                (
                    "is_suggested",
                    models.BooleanField(default=False, verbose_name="پیشنهادی"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("option", "Option"),
                            ("multi_option", "Multi Option"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "option_group",
                    models.ForeignKey(
                        blank=True,
                        help_text='Select an option group if using type "Option" or "Multi Option"',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Shop.optiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute",
                "verbose_name_plural": "Product Attributes",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        height_field="height",
                        null=True,
                        upload_to="Products/",
                        width_field="width",
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=512, null=True)),
                ("width", models.IntegerField(blank=True, editable=False, null=True)),
                ("height", models.IntegerField(blank=True, editable=False, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصویر های محصول",
                "ordering": ("display_order",),
            },
        ),
        migrations.CreateModel(
            name="ProductClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                ("track_stock", models.BooleanField(default=True)),
                ("require_shipping", models.BooleanField(default=True)),
                ("options", models.ManyToManyField(blank=True, to="Shop.option")),
            ],
            options={
                "verbose_name": "Product Class",
                "verbose_name_plural": "Product Classes",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_integer", models.IntegerField(blank=True, null=True)),
                ("value_float", models.FloatField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shop.productattribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Shop.product"
                    ),
                ),
                (
                    "value_multi_option",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_valued_attribute_value",
                        to="Shop.optiongroupvalue",
                    ),
                ),
                (
                    "value_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Shop.optiongroupvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Value",
                "verbose_name_plural": "Attribute Values",
                "unique_together": {("product", "attribute")},
            },
        ),
        migrations.AddField(
            model_name="productattribute",
            name="product_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="Shop.productclass",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                help_text="A product attribute defines a feature the product may have, like size...",
                through="Shop.ProductAttributeValue",
                to="Shop.productattribute",
                verbose_name="ویژگی ها",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories",
                to="Shop.category",
                verbose_name="دسته بندی ها",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="Shop.product",
                verbose_name="زیر دسته",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="Shop.productclass",
                verbose_name="کلاس محصول",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_options",
            field=models.ManyToManyField(
                blank=True,
                help_text="Options are values that can be associated with a item something like a personalised message to be printed on a T-shirt.",
                to="Shop.option",
                verbose_name="گزینه ها",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="option_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="Shop.optiongroup",
            ),
        ),
    ]
