# Generated by Django 4.2.18 on 2025-02-08 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0002_order_orderdetail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdetail",
            options={
                "verbose_name": "جزئیات سفارش",
                "verbose_name_plural": "جزئیات سفارشات",
            },
        ),
    ]
