# Generated by Django 4.2.18 on 2025-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0003_alter_orderdetail_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optiongroupvalue",
            name="group",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="option_group",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="product_class",
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="attribute",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="value_multi_option",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="value_option",
        ),
        migrations.RemoveField(
            model_name="productclass",
            name="options",
        ),
        migrations.RemoveField(
            model_name="product",
            name="attributes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_class",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_options",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="رنگ"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="extra_features",
            field=models.TextField(
                blank=True, null=True, verbose_name="ویژگی های بیشتر"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="جنس"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="اندازه"
            ),
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="OptionGroup",
        ),
        migrations.DeleteModel(
            name="OptionGroupValue",
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
        migrations.DeleteModel(
            name="ProductAttributeValue",
        ),
        migrations.DeleteModel(
            name="ProductClass",
        ),
    ]
